<?php
declare(strict_types=1);

/**
 * OpenDXP
 *
 * This source file is licensed under the GNU General Public License version 3 (GPLv3).
 *
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 * @copyright  Copyright (c) Pimcore GmbH (https://pimcore.com)
 * @copyright  Modification Copyright (c) OpenDXP (https://www.opendxp.io)
 * @license    https://www.gnu.org/licenses/gpl-3.0.html  GNU General Public License version 3 (GPLv3)
 */

namespace OpenDxp\Bundle\DataHubBundle\GraphQL\DataObjectQueryOperatorConfigGenerator;

use GraphQL\Type\Definition\Type;
use OpenDxp\Bundle\DataHubBundle\GraphQL\DataObjectQueryFieldConfigGenerator\ImageGallery;
use OpenDxp\Bundle\DataHubBundle\GraphQL\Resolver;
use Override;

/**
 * Class ThumbnailHtml
 *
 * @package OpenDxp\Bundle\DataHubBundle\GraphQL\QueryOperatorConfigGenerator
 */
class ThumbnailHtml extends Base
{
    /**
     * @param array $config
     * @param object|null $container
     *
     * @return mixed
     */
    #[Override]
    public function enrichConfig($config, $container = null)
    {
        $config['description'] = 'A thumbnail HTML snippet which contains the entire image editable as generated by OpenDXP';

        // If the resolver is an array, this should be configured as a listOf(strings) type instead of a single string type
        if ($config['resolve'][0] instanceof Resolver\Base) {
            /** @var Resolver\Base $cResolver */
            $cResolver = $config['resolve'][0];
            if ($cResolver->getResolverAttribute('dataType') === ImageGallery::TYPE) {
                $config['type'] = Type::listOf(Type::string());
                $config['description'] = 'A list of thumbnail HTML snippets which contains the entire image editables of the gallery as generated by OpenDXP';
            }
        }

        return parent::enrichConfig($config, $container);
    }
}
